# Generated by Django 4.1.4 on 2023-07-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_subscribre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribre',
            new_name='Subscribe',
        ),
    ]
