# Generated by Django 4.1.4 on 2023-07-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_subscribre_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
